### ISSUE TITLE
Compatibility .net core 2.1

### ISSUE THREAD

**Issue by annayafi** [geeklearningio/gl-dotnet-domain#49]
I get 
`TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Internal.IHttpResponseStreamWriterFactory' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

when adding : 
```.AddDomainExceptions()``` in `ConfigureServices`

Since upgrading my web app to .net core 2.1

**Comment by asiffermann** [comment]
We just published a release ([0.4.0](https://github.com/geeklearningio/gl-dotnet-domain/releases/tag/0.4.0)) on NuGet that fixes your issue upgrading all our libraries to NETStandard 2.0! 🎉
